projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: https://heroku-demo-32548.herokuapp.com/heroku/demo
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml